### ISSUE TITLE
Prisma

### ISSUE THREAD

**Issue by NicoDora** [fashion24-developer/fashion24-back#10]
## 개요

- prisma 초기 설정 하기

## 작업 목록

- [x] prisma 설치
- [x] prisma DB와 연결
- [x] .env 파일 설정
- [x] prisma schema 모델 만들기

**Comment by 2swo** [comment]
Could not create branch `/#10/Prisma` due to: refs/heads//#10/Prisma is not a valid ref name. - https://docs.github.com/rest/git/refs#create-a-reference
