### ISSUE TITLE
nestjs application setup

### ISSUE THREAD

**Issue by hobiJeong** [fashion24-developer/fashion24-back#4]
## 개요

- NestJS server application setup

## 작업 목록

- [x] tsconfig
- [x] eslint
- [x] prettier

## 참고

- 기본적인 것만 setup 하고 ExceptionLayer, Logger 등등은 작업 단위를 분리 하겠습니다.

**Comment by 2swo** [comment]
Could not create branch `/#4/nestjs_application_setup` due to: refs/heads//#4/nestjs_application_setup is not a valid ref name. - https://docs.github.com/rest/git/refs#create-a-reference

**Comment by 2swo** [comment]
Branch setting/#4/nestjs_application_setup created for issue: nestjs application setup
