### ISSUE TITLE
initial module configuration

### ISSUE THREAD

**Issue by hobiJeong** [fashion24-developer/fashion24-back#6]
## 개요

- 초기 모듈 및 LoggerMiddleware, ExceptionFilter, CustomValidationPipe, Clean Architecture를 구성하기 위한 인터페이스 등을 미리 구성합니다.

## 작업 목록

- [x] CoreModule
  - [x] type-safe ConfigModule
- [x] ApiModule
- [x] LoggerMiddleware
- [x] ExceptionFilter
- [x] CustomValidationPipe
- [x] interface

## 참고

- type-safe ConfigModule과 LoggerMiddleware는 기존 Menbosha 서버에서 사용하던 코드를 그대로 가져옵니다.
- ApiModule은 당장에는 깡통 모듈이지만 모듈 구조를 잡아 놓기 위해 미리 구성합니다.
  - 이름 그대로 Api관련 Root Module
- ExceptionFilter는 당장에는 하나만 구성하지만 이커머스 서비스의 경우에 error case가 굉장히 많을 것 같아서 추후에 custom한 error code와 함께 사용할 수 있도록 코드를 수정하는 게 좋을 것 같습니다.
- 기존 ValidationPipe는 global 레벨로 적용한 후 하위 레벨에서는 option 재정의가 불가한데 이를 보완한 CustomValidationPipe를 생성합니다.

**Comment by 2swo** [comment]
Branch setting/#6/Initial_module_configurat created for issue: Initial module configuration
