### ISSUE TITLE
Fancy 관련한 테이블 구조 변경, 그에 따른 로직 수정

### ISSUE THREAD

**Issue by Contingency1** [fashion24-developer/fashion24-back#66]
## 개요
- option과 sub-option 간의 관계에서 Issue가 발생함에 따른 option, suboption 관련 테이블 삭제 
- fancy table에 json 형식의 option, sub-option 관련 data를 담는 것 추가.
- 그에 따라 발생하는 로직 수정

## 작업 목록

- [ ] fancy 관련 table 변경
- [ ] 관련로직 수정

**Comment by hobiJeong** [comment]
Branch setting/#66/Fancy_관련한_테이블_구조_변경_그에_따 created for issue: Fancy 관련한 테이블 구조 변경, 그에 따른 로직 수정
