### ISSUE TITLE
fancy_pagination

### ISSUE THREAD

**Issue by Contingency1** [fashion24-developer/fashion24-back#67]
## 개요

- 프론트 요청으로 fancy 관련 반환값 가공합니다.
- fancy 테이블 updatedAt default값 설정

## 작업 목록

- [ ] fancy pagination 조회 반환값 변경
- [ ] fancy 테이블 updatedAt default 값 설정
- [ ] 관련 리팩토링 수행

**Comment by hobiJeong** [comment]
Branch modify/#67/fancy_pagination created for issue: fancy_pagination
