### ISSUE TITLE
modify table

### ISSUE THREAD

**Issue by Contingency1** [fashion24-developer/fashion24-back#70]
## 개요

- 기획 추가 및 수정에 따른 테이블을 추가, 수정합니다.

## 작업 목록

- [ ] fancy에 대한 review table 추가
- [ ] 유저주소 테이블 삭제 + 유저 테이블에 주소 스키마 추가
- [ ] address 테이블 삭제
- [ ] 유저에 address 스키마추가
- [ ] 유저에 gender, birth 스키마 추가
- [ ] 폭넓게 대폭 수정

## 참고

- 추가로 작업할 것들 말씀해주세요

**Comment by hobiJeong** [comment]
Branch setting/#70/modify_table created for issue: modify table
