### ISSUE TITLE
cicd bug fix

### ISSUE THREAD

**Issue by NicoDora** [fashion24-developer/fashion24-back#73]
## 개요

- CI / CD 작업중에 기존 이미지 파일이 제대로 삭제되지 않는 문제 해결하기

## 작업 목록

- [x] CI / CD 작업중에 기존 이미지 파일이 제대로 삭제되지 않는 문제 해결하기

## 참고

- 작업하면서 참고한 레퍼런스 문서 등 추가

**Comment by hobiJeong** [comment]
Branch Deploy/#73/cicd_bug_fix created for issue: cicd bug fix
