### ISSUE TITLE
login bug fix

### ISSUE THREAD

**Issue by NicoDora** [fashion24-developer/fashion24-back#75]
## 개요

- 유저가 로그아웃을 하지 않고 재 로그인 하면 에러가 발생하는 버그 수정하기

## 작업 목록

- [x] 유저가 로그아웃을 하지 않고 재 로그인 하면 에러가 발생하는 버그 수정하기

## 참고

- 작업하면서 참고한 레퍼런스 문서 등 추가

**Comment by hobiJeong** [comment]
Branch bugfix/#75/login_bug_fix created for issue: login bug fix
